### ISSUE TITLE
issue 2 (adding a fridge to the kitchen)

### ISSUE THREAD

**Issue by lucasthierry17** [ZDDduesseldorf/zdd_adventure2023#2]
There should be a fridge in the kitchen. 
It should include these ingredients: [eggs, pasta, rice, bread, ice cream] and any other you like!
Don't forget to eat something in the kitchen...

**Comment by tis22** [comment]
assignee: @tis22 (assignment not possible)

**Comment by tis22** [comment]
I added the fridge as you wished. 
Moreover the user can eat the items from your list now, they are stored in the fridge.
Lots of items!
